sonar.projectKey=b2u-front-candidature
sonar.projectName=B2U Front - Candidature
sonar.sourceEncoding=UTF-8

sonar.sources=src/app/core/services/candidature.service.ts,src/app/core/models/candidature.model.ts,src/app/features/candidatures/candidature-form.ts,src/app/features/candidatures/candidature-form.html,src/app/features/candidatures/candidature-form.scss
sonar.tests=src/app/core/services/candidature.service.spec.ts,src/app/features/candidatures/candidature-form.spec.ts
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/b2u-hub/lcov.info
sonar.dependencyCheck.jsonReportPath=reports/owasp/front/dependency-check-report.json
sonar.dependencyCheck.htmlReportPath=reports/owasp/front/dependency-check-report.html
